# flake8: noqa
# type: ignore
# pylint: skip-file
prefixes  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:17)
prefix_distance_infty_norm  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:41)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:71)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:76)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:81)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:86)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:96)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:101)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:106)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:111)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:130)
_  # unused function (src/pdfa_learning/learn_pdfa/utils/base.py:136)
SimpleGenerator  # unused class (src/pdfa_learning/learn_pdfa/utils/generator.py:25)
MultiprocessedGenerator  # unused class (src/pdfa_learning/learn_pdfa/utils/generator.py:43)
_.elements  # unused method (src/pdfa_learning/learn_pdfa/utils/multiset/base.py:43)
_._parent  # unused attribute (src/pdfa_learning/learn_pdfa/utils/multiset/tree.py:39)
node_to_graphviz  # unused function (src/pdfa_learning/learn_pdfa/utils/multiset/tree.py:271)
_.get_successor  # unused method (src/pdfa_learning/pdfa/base.py:52)
_.final_symbol  # unused property (src/pdfa_learning/pdfa/base.py:102)
to_graphviz  # unused function (src/pdfa_learning/pdfa/render.py:15)
to_graphviz_from_graph  # unused function (src/pdfa_learning/pdfa/render.py:57)
